"use client";
import { apiPath } from "@/lib/paths";
import { useEffect, useMemo, useState } from "react";
import { CalendarDays, Users, Dumbbell, Wallet, ShoppingBag, Package, Plus, ChevronLeft, ChevronRight, X, Search, Pencil, Trash2 } from "lucide-react";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";

type Kind = "athlete" | "exercise" | "structure" | "session" | "payment" | "product" | "order";
type Rec = { id: string; kind: Kind; createdAt?: number; [key: string]: any };
const nav = [{ key:"agenda", title:"Agenda", icon:CalendarDays },{ key:"atletas", title:"Atletas", icon:Users },{ key:"rutinas", title:"Rutinas", icon:Dumbbell },{ key:"finanzas", title:"Finanzas", icon:Wallet },{ key:"productos", title:"Productos", icon:ShoppingBag },{ key:"pedidos", title:"Pedidos", icon:Package }] as const;
const categories = ["Empuje","Tracción","Dominante de cadera","Dominante de rodilla","Core","Metabólico"];
const modalities = ["1 a 1","Grupal","Evaluación física","En línea"];
const goals = ["Fuerza","Reacondicionamiento","Pérdida de grasa","Rendimiento","Movilidad"];
const color: Record<string,string> = {"1 a 1":"#a5ed34","Grupal":"#45bdf4","Evaluación física":"#f5bf37","En línea":"#e17ae5"};
const money = (n:any) => new Intl.NumberFormat("es-MX",{style:"currency",currency:"MXN"}).format(Number(n)||0);
const dateKey = (d:Date) => `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
const today = () => dateKey(new Date());
const niceDate = (s:string, opts: Intl.DateTimeFormatOptions = {weekday:"long",day:"numeric",month:"long"}) => new Date(`${s}T12:00:00`).toLocaleDateString("es-MX",opts);
function Field({label,children,full=false}:{label:string;children:React.ReactNode;full?:boolean}) { return <label className={`field ${full?"full":""}`}><span>{label}</span>{children}</label>; }
function Empty({children}:{children:React.ReactNode}) { return <div className="empty">{children}</div>; }

export default function Home(){
 const [section,setSection]=useState<typeof nav[number]["key"]>("agenda"); const [records,setRecords]=useState<Rec[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
 const [modal,setModal]=useState<Kind|null>(null); const [editing,setEditing]=useState<Rec|null>(null); const [form,setForm]=useState<Record<string,any>>({});
 const [day,setDay]=useState(today()); const [calendarView,setCalendarView]=useState("Semana"); const [dayOpen,setDayOpen]=useState(false);
 const [routineTab,setRoutineTab]=useState("Ejercicios"); const [category,setCategory]=useState("Todos"); const [productCategory,setProductCategory]=useState("Todos"); const [query,setQuery]=useState(""); const [cart,setCart]=useState<{id:string;qty:number}[]>([]); const [cartOpen,setCartOpen]=useState(false);
 useEffect(()=>{ fetch(apiPath()).then(async r=>{const j:any=await r.json(); if(!r.ok) throw new Error(j.error||"No se pudieron cargar los datos"); setRecords(j.records||[]);}).catch(e=>setError(e.message)).finally(()=>setLoading(false)); },[]);
 useEffect(()=>{const context=(document as Document & {modelContext?: {registerTool:(tool:any, options:any)=>void|Promise<void>}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();Promise.resolve(context.registerTool({name:"open_fitness_section",title:"Abrir sección",description:"Abre una sección del panel de Owen's Fitness.",inputSchema:{type:"object",properties:{section:{type:"string",enum:nav.map(x=>x.key)}},required:["section"],additionalProperties:false},annotations:{readOnlyHint:true},execute(input:{section:string}){if(!nav.some(x=>x.key===input.section))throw new Error("Sección desconocida");setSection(input.section as typeof section);return {section:input.section}}},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort()},[]);
 const by=(kind:Kind)=>records.filter(r=>r.kind===kind);
 function open(kind:Kind,record:Rec|null=null){setEditing(record); setForm(record?{...record}:{date:day,type:"Sesión",modality:"1 a 1",start:"07:00",end:"08:00",capacity:1,cancelHours:4,format:"AMRAP",minutes:20,level:"Intermedio",moves:[{exerciseId:"",reps:"",load:"",rpe:""}],category:"Suplementación",minStock:3,variants:[{name:"Único",stock:0,priceDelta:0}],status:"Pagado",method:"Efectivo",recurrence:"Ninguna",fulfillment:"Recoger en estudio"});setModal(kind);}
 function value(k:string,v:any){setForm(f=>({...f,[k]:v}));}
 async function save(e:React.FormEvent){e.preventDefault(); if(!modal) return;setBusy(true);setError("");try{const payload={...form};delete payload.id;delete payload.kind;delete payload.createdAt;
  const r=await fetch(apiPath(),{method:editing?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(editing?{id:editing.id,data:payload}:{kind:modal,data:payload})});const j:any=await r.json();if(!r.ok) throw new Error(j.error||"No se pudo guardar");
  setRecords(prev=>editing?prev.map(x=>x.id===editing.id?{...x,...j}:x):[{...j.record},...prev]);setModal(null);
 }catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function remove(r:Rec){if(!window.confirm(`¿Eliminar ${r.name||r.title||"este registro"}?`))return;try{const response=await fetch(`${apiPath()}?id=${encodeURIComponent(r.id)}`,{method:"DELETE"});if(!response.ok)throw new Error("No se pudo eliminar");setRecords(prev=>prev.filter(x=>x.id!==r.id));}catch(e:any){setError(e.message)}}
 async function update(r:Rec,data:Record<string,any>){try{const response=await fetch(apiPath(),{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:r.id,data})});const j:any=await response.json();if(!response.ok)throw new Error(j.error);setRecords(prev=>prev.map(x=>x.id===r.id?{...x,...j}:x));}catch(e:any){setError(e.message)}}
 const sessions=by("session");const dayItems=sessions.filter(r=>r.date===day).sort((a,b)=>String(a.start).localeCompare(String(b.start)));
 const week=useMemo(()=>{const d=new Date(`${day}T12:00:00`);const wd=(d.getDay()+6)%7;d.setDate(d.getDate()-wd);return Array.from({length:7},(_,i)=>{const x=new Date(d);x.setDate(d.getDate()+i);return dateKey(x)})},[day]);
 function shift(n:number){const d=new Date(`${day}T12:00:00`);d.setDate(d.getDate()+n*(calendarView==="Mes"?30:calendarView==="Semana"?7:1));setDay(dateKey(d));}
 const paid=by("payment").filter(x=>String(x.status).toLowerCase()==="pagado"&&String(x.date||x.createdAt&&dateKey(new Date(x.createdAt))).slice(0,7)===today().slice(0,7)).reduce((s,x)=>s+Number(x.amount||0),0);
 const due=by("payment").filter(x=>String(x.status).toLowerCase()!=="pagado").reduce((s,x)=>s+Number(x.amount||0),0);
 const projected=by("payment").filter(x=>x.recurrence&&x.recurrence!=="Ninguna").reduce((s,x)=>s+Number(x.amount||0),0);
 const sales=by("order").filter(x=>!["Pendiente","Cancelado"].includes(x.status)).reduce((s,x)=>s+Number(x.total||0),0);
 const cartTotal=cart.reduce((s,x)=>s+(Number(by("product").find(p=>p.id===x.id)?.price)||0)*x.qty,0);
 async function placeOrder(e:React.FormEvent){e.preventDefault();setBusy(true);try{const data={name:form.customer||"",fulfillment:form.fulfillment||"Recoger en estudio",method:form.method||"Efectivo",status:"Pendiente",items:cart.map(x=>{const p=by("product").find(y=>y.id===x.id);return {productId:x.id,name:p?.name,qty:x.qty,unitPrice:Number(p?.price)||0}}),total:cartTotal,date:today()};if(!data.name.trim())throw new Error("Indica el nombre del cliente");for(const item of cart){const p=by("product").find(x=>x.id===item.id);if(!p)throw new Error("Un producto ya no está disponible");const stock=(p.variants||[]).reduce((s:number,v:any)=>s+Number(v.stock||0),0);if(!p.digital&&item.qty>stock)throw new Error(`Stock insuficiente de ${p.name}`)}const r=await fetch(apiPath(),{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind:"order",data})});const j:any=await r.json();if(!r.ok)throw new Error(j.error);setRecords(prev=>[j.record,...prev]);setCart([]);setCartOpen(false);setSection("pedidos");}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <div className="app-shell"><aside className="side"><div className="brand"><span className="brand-mark">O</span><span>OWEN’S<br/><b>FITNESS</b></span></div><nav aria-label="Secciones">{nav.map(({key,title,icon:Icon})=><button key={key} className={section===key?"active":""} onClick={()=>{setSection(key);setError("")}}><Icon size={21}/><span>{title}</span></button>)}</nav><div className="side-foot">Panel de entrenamiento<br/><button className="secondary" onClick={async()=>{await fetch(`${process.env.NEXT_PUBLIC_BASE_PATH || ""}/api/logout`,{method:"POST"}); window.location.href=`${process.env.NEXT_PUBLIC_BASE_PATH || ""}/login`;}}>Cerrar sesión</button></div></aside>
 <main className="main">{error&&<div className="notice error" role="alert">{error}<button onClick={()=>setError("")} aria-label="Cerrar"><X size={16}/></button></div>}{loading?<Empty>Cargando registros…</Empty>:<>
 {section==="agenda"&&<><header className="page-head"><div><h1>Agenda y control<br className="mobile-break"/> de citas</h1><p>Sesiones y bloqueos de tiempo.</p></div><button className="primary" onClick={()=>open("session")}><Plus size={20}/> Nuevo</button></header><div className="date-nav"><button onClick={()=>shift(-1)} aria-label="Anterior"><ChevronLeft/></button><strong>{niceDate(day,{day:"numeric",month:"long",year:"numeric"})}</strong><button onClick={()=>shift(1)} aria-label="Siguiente"><ChevronRight/></button></div><Tabs value={calendarView} onValueChange={setCalendarView}><TabsList className="pill-tabs">{["Día","Semana","Mes"].map(x=><TabsTrigger key={x} value={x}>{x}</TabsTrigger>)}</TabsList></Tabs><div className="legend">{modalities.map(x=><span key={x}><i style={{background:color[x]}}/>{x}</span>)}</div><div className={`calendar ${calendarView==="Mes"?"month":""}`}>{(calendarView==="Día"?[day]:calendarView==="Semana"?week:Array.from({length:new Date(Number(day.slice(0,4)),Number(day.slice(5,7)),0).getDate()},(_,i)=>`${day.slice(0,7)}-${String(i+1).padStart(2,"0")}`)).map(d=><button key={d} className={`date-cell ${day===d?"selected":""}`} onClick={()=>{setDay(d);setDayOpen(true)}}><small>{niceDate(d,{weekday:"short"})}</small><b>{Number(d.slice(-2))}</b><div className="event-dots">{sessions.filter(x=>x.date===d).slice(0,4).map(x=><i key={x.id} style={{background:color[x.modality]||"#777"}}/>)}</div></button>)}</div><section className="day-list"><h2>{niceDate(day)}</h2>{dayItems.length?dayItems.map(r=><div className="list-card" key={r.id}><span className="session-stripe" style={{background:color[r.modality]||"#777"}}/><div><b>{r.title||"Bloqueo de tiempo"}</b><p>{r.start}–{r.end} · {r.type==="Bloqueo de tiempo"?"Bloqueo":r.modality}{r.place?` · ${r.place}`:""}</p></div><div className="actions"><button aria-label="Editar" onClick={()=>open("session",r)}><Pencil size={18}/></button><button aria-label="Eliminar" onClick={()=>remove(r)}><Trash2 size={18}/></button></div></div>):<Empty>Sin actividad este día. Crea una sesión o bloquea tu tiempo.</Empty>}</section></>}
 {section==="atletas"&&<><header className="page-head"><div><h1>Gestión de atletas</h1><p>Ficha, objetivos y paquetes.</p></div><button className="primary" onClick={()=>open("athlete")}><Plus size={20}/> Nuevo atleta</button></header><label className="search"><Search size={19}/><input placeholder="Buscar atleta…" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="cards">{by("athlete").filter(x=>String(x.name||"").toLowerCase().includes(query.toLowerCase())).map(r=><article className="card" key={r.id}><div className="card-top"><h2>{r.name}</h2><div className="actions"><button onClick={()=>open("athlete",r)} aria-label="Editar"><Pencil size={18}/></button><button onClick={()=>remove(r)} aria-label="Eliminar"><Trash2 size={18}/></button></div></div><p>{r.phone||"Sin teléfono"}{r.email?` · ${r.email}`:""}</p><div className="tags">{(r.goals||[]).map((g:string)=><span key={g}>{g}</span>)}</div><div className="card-meta">{r.package||"Sin paquete"} · {Number(r.credits||0)+by("payment").filter(p=>p.athleteId===r.id&&p.status==="Pagado").reduce((s,p)=>s+Number(p.creditAmount||0),0)} créditos{r.expires?` · Vence ${r.expires}`:""}</div></article>)}{!by("athlete").length&&<Empty>Sin atletas todavía.</Empty>}</div></>}
 {section==="rutinas"&&<><header className="page-head"><div><h1>Rutinas y programación</h1><p>Ejercicios y estructuras para la agenda.</p></div><button className="primary" onClick={()=>open(routineTab==="Ejercicios"?"exercise":"structure")}><Plus size={20}/> {routineTab==="Ejercicios"?"Ejercicio":"Estructura"}</button></header><Tabs value={routineTab} onValueChange={setRoutineTab}><TabsList className="pill-tabs"><TabsTrigger value="Ejercicios">Ejercicios</TabsTrigger><TabsTrigger value="Estructuras">Estructuras</TabsTrigger></TabsList></Tabs>{routineTab==="Ejercicios"?<><div className="filters">{["Todos",...categories].map(x=><button key={x} className={category===x?"chosen":""} onClick={()=>setCategory(x)}>{x}</button>)}</div><div className="cards">{by("exercise").filter(x=>category==="Todos"||x.category===category).map(r=><article className="card" key={r.id}><div className="card-top"><small className="eyebrow">{r.category}</small><div className="actions"><button onClick={()=>open("exercise",r)} aria-label="Editar"><Pencil size={18}/></button><button onClick={()=>remove(r)} aria-label="Eliminar"><Trash2 size={18}/></button></div></div><h2>{r.name}</h2><p>{r.level} · {r.equipment||"Sin equipo"}</p><p>{r.notes}</p>{r.link&&<a href={r.link} target="_blank" rel="noopener noreferrer">Ver contenido adjunto</a>}</article>)}{!by("exercise").filter(x=>category==="Todos"||x.category===category).length&&<Empty>No hay ejercicios en esta categoría.</Empty>}</div></>:<div className="cards">{by("structure").map(r=><article className="card" key={r.id}><div className="card-top"><span className="format">{r.format}</span><div><small>{r.minutes} min</small><span className="actions"><button onClick={()=>open("structure",r)} aria-label="Editar"><Pencil size={18}/></button><button onClick={()=>remove(r)} aria-label="Eliminar"><Trash2 size={18}/></button></span></div></div><h2>{r.name}</h2><p>{r.description}</p><ul>{(r.moves||[]).map((m:any,i:number)=><li key={i}>{by("exercise").find(x=>x.id===m.exerciseId)?.name||"Ejercicio"} · {m.reps} {m.load&&`· ${m.load}`} {m.rpe&&`· RPE ${m.rpe}`}</li>)}</ul><small>Vincúlala a una sesión desde la Agenda.</small></article>)}{!by("structure").length&&<Empty>Sin estructuras todavía. Crea una con tus ejercicios.</Empty>}</div>}</>}
 {section==="finanzas"&&<><header className="page-head"><div><h1>Finanzas y cobranza</h1><p>Pagos y proyección del mes.</p></div><button className="primary" onClick={()=>open("payment")}><Plus size={20}/> Registrar cobro</button></header><div className="metrics">{[["Cobrado este mes",paid],["Por cobrar",due],["Recurrente proyectado",projected],["Ventas de tienda",sales]].map(([label,n])=><div className="metric" key={String(label)}><small>{label}</small><strong>{money(n)}</strong></div>)}</div><div className="notice amber">Alertas de cobro · {due?`${money(due)} pendiente de pago`:"Sin saldos pendientes"}</div><h2>Movimientos</h2>{by("payment").map(r=><div className="list-card" key={r.id}><div><b>{r.concept}</b><p>{by("athlete").find(x=>x.id===r.athleteId)?.name||"Atleta"} · {r.date||"Sin fecha"} · {r.method}</p></div><strong>{money(r.amount)}</strong><span className="status">{r.status}</span><div className="actions"><button onClick={()=>open("payment",r)} aria-label="Editar"><Pencil size={18}/></button><button onClick={()=>remove(r)} aria-label="Eliminar"><Trash2 size={18}/></button></div></div>)}{!by("payment").length&&<Empty>Sin movimientos registrados.</Empty>}</>}
 {section==="productos"&&<><header className="page-head"><div><h1>Productos oficiales</h1><p>Suplementación, ropa y programas digitales.</p></div><div className="head-actions"><button className="secondary" onClick={()=>open("product")}><Plus size={18}/> Nuevo producto</button><button className="primary" onClick={()=>{setForm({});setCartOpen(true)}}>Carrito ({cart.reduce((s,x)=>s+x.qty,0)})</button></div></header><div className="filters">{["Todos","Suplementación","Ropa y Accesorios","Programas Digitales"].map(x=><button key={x} className={productCategory===x?"chosen":""} onClick={()=>setProductCategory(x)}>{x}</button>)}</div><div className="product-grid">{by("product").filter(x=>productCategory==="Todos"||x.category===productCategory).map(r=><article className="product-card" key={r.id}>{r.imageUrl?<img src={r.imageUrl} alt={r.name}/>:<div className="product-image"><ShoppingBag size={42}/></div>}<div className="product-body"><div className="card-top"><small className="eyebrow">{r.category}</small><div className="actions"><button onClick={()=>open("product",r)} aria-label="Editar"><Pencil size={18}/></button><button onClick={()=>remove(r)} aria-label="Eliminar"><Trash2 size={18}/></button></div></div><h2>{r.name}</h2><p>{r.description}</p><div className="tags">{(r.variants||[]).map((v:any,i:number)=><span key={i}>{v.name}</span>)}</div><div className="product-bottom"><div><strong>{money(r.price)}</strong><small>{r.digital?"Digital":`${(r.variants||[]).reduce((s:number,v:any)=>s+Number(v.stock||0),0)} en stock`}</small></div><button className="primary" onClick={()=>setCart(c=>{const existing=c.find(x=>x.id===r.id);return existing?c.map(x=>x.id===r.id?{...x,qty:x.qty+1}:x):[...c,{id:r.id,qty:1}]})}>Agregar</button></div></div></article>)}{!by("product").length&&<Empty>Sin productos todavía.</Empty>}</div></>}
 {section==="pedidos"&&<><header className="page-head"><div><h1>Pedidos</h1><p>Seguimiento y entrega de compras.</p></div></header><div className="cards">{by("order").map(r=><article className="card" key={r.id}><div className="card-top"><h2>{r.name}</h2><strong>{money(r.total)}</strong></div><p>{r.fulfillment} · {r.method} · {r.date}</p><div className="order-items">{(r.items||[]).map((item:any,i:number)=><div key={i}>{item.name} × {item.qty}<span>{money(item.unitPrice*item.qty)}</span></div>)}</div><div className="order-footer"><label>Estado <select value={r.status} onChange={e=>update(r,{status:e.target.value})}>{["Pendiente","Pagado","Preparando","Listo","Entregado","Cancelado"].map(x=><option key={x}>{x}</option>)}</select></label><button className="icon-danger" onClick={()=>remove(r)} aria-label="Eliminar pedido"><Trash2 size={18}/></button></div></article>)}{!by("order").length&&<Empty>Sin pedidos todavía. Los pedidos nuevos aparecerán aquí.</Empty>}</div></>}
 </>}</main><nav className="bottom-nav" aria-label="Secciones">{nav.map(({key,title,icon:Icon})=><button key={key} className={section===key?"active":""} onClick={()=>setSection(key)}><Icon size={21}/><span>{title}</span></button>)}</nav>
 <Dialog open={!!modal} onOpenChange={v=>{if(!v)setModal(null)}}><DialogContent className="editor"><DialogHeader><DialogTitle>{editing?"Editar":"Nuevo"} {modal==="athlete"?"atleta":modal==="exercise"?"ejercicio":modal==="structure"?"estructura de entrenamiento":modal==="session"?"en agenda":modal==="payment"?"cobro":modal==="product"?"producto":"pedido"}</DialogTitle></DialogHeader><form onSubmit={save} className="form-grid">
 {modal==="athlete"&&<><Field label="Nombre completo" full><input required value={form.name||""} onChange={e=>value("name",e.target.value)}/></Field><Field label="Teléfono"><input type="tel" value={form.phone||""} onChange={e=>value("phone",e.target.value)}/></Field><Field label="Correo"><input type="email" value={form.email||""} onChange={e=>value("email",e.target.value)}/></Field><div className="full"><span className="label">Objetivos</span><div className="filters">{goals.map(g=><button type="button" key={g} className={(form.goals||[]).includes(g)?"chosen":""} onClick={()=>value("goals",(form.goals||[]).includes(g)?form.goals.filter((x:string)=>x!==g):[...(form.goals||[]),g])}>{g}</button>)}</div></div>{[["Historial médico","medical"],["Lesiones activas","injuries"],["Limitaciones de movilidad","mobility"]].map(([label,key])=><Field key={key} label={label} full><textarea value={form[key]||""} onChange={e=>value(key,e.target.value)}/></Field>)}<Field label="Paquete"><input value={form.package||""} onChange={e=>value("package",e.target.value)}/></Field><Field label="Créditos"><input type="number" min="0" value={form.credits||0} onChange={e=>value("credits",e.target.value)}/></Field><Field label="Vence"><input type="date" value={form.expires||""} onChange={e=>value("expires",e.target.value)}/></Field></>}
 {modal==="exercise"&&<><Field label="Nombre" full><input required value={form.name||""} onChange={e=>value("name",e.target.value)}/></Field><Field label="Categoría"><select value={form.category||"Empuje"} onChange={e=>value("category",e.target.value)}>{categories.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Nivel"><select value={form.level||"Principiante"} onChange={e=>value("level",e.target.value)}>{["Principiante","Intermedio","Avanzado"].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Equipo"><input value={form.equipment||""} onChange={e=>value("equipment",e.target.value)}/></Field><Field label="Enlace de contenido"><input type="url" value={form.link||""} onChange={e=>value("link",e.target.value)}/></Field><Field label="Indicaciones" full><textarea value={form.notes||""} onChange={e=>value("notes",e.target.value)}/></Field></>}
 {modal==="structure"&&<><Field label="Nombre" full><input required value={form.name||""} onChange={e=>value("name",e.target.value)}/></Field><Field label="Formato"><select value={form.format||"AMRAP"} onChange={e=>value("format",e.target.value)}>{["AMRAP","Tabata","Fuerza RPE","EMOM","Por tiempo","Otro"].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Minutos"><input type="number" min="1" value={form.minutes||20} onChange={e=>value("minutes",e.target.value)}/></Field><Field label="Nivel" full><select value={form.level||"Intermedio"} onChange={e=>value("level",e.target.value)}>{["Principiante","Intermedio","Avanzado"].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Descripción / score" full><textarea value={form.description||""} onChange={e=>value("description",e.target.value)}/></Field><div className="full"><span className="label">Movimientos</span>{(form.moves||[]).map((m:any,i:number)=><div className="move-grid" key={i}><select value={m.exerciseId||""} onChange={e=>value("moves",form.moves.map((x:any,j:number)=>j===i?{...x,exerciseId:e.target.value}:x))}><option value="">Ejercicio…</option>{by("exercise").map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select>{["reps","load","rpe"].map(k=><input key={k} placeholder={k==="reps"?"Reps":k==="load"?"Carga":"RPE"} value={m[k]||""} onChange={e=>value("moves",form.moves.map((x:any,j:number)=>j===i?{...x,[k]:e.target.value}:x))}/>)}<button type="button" aria-label="Quitar movimiento" onClick={()=>value("moves",form.moves.filter((_:any,j:number)=>j!==i))}><X size={17}/></button></div>)}<button type="button" className="secondary" onClick={()=>value("moves",[...(form.moves||[]),{exerciseId:"",reps:"",load:"",rpe:""}])}><Plus size={16}/> Añadir movimiento</button></div></>}
 {modal==="session"&&<><Field label="Fecha"><input type="date" required value={form.date||day} onChange={e=>value("date",e.target.value)}/></Field><Field label="Tipo"><select value={form.type||"Sesión"} onChange={e=>value("type",e.target.value)}><option>Sesión</option><option>Bloqueo de tiempo</option></select></Field><Field label="Título" full><input required value={form.title||""} onChange={e=>value("title",e.target.value)}/></Field>{form.type!=="Bloqueo de tiempo"&&<><Field label="Modalidad"><select value={form.modality||"1 a 1"} onChange={e=>value("modality",e.target.value)}>{modalities.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Cupo máximo"><input type="number" min="1" value={form.capacity||1} onChange={e=>value("capacity",e.target.value)}/></Field><Field label="Margen cancelación (h)"><input type="number" min="0" value={form.cancelHours||0} onChange={e=>value("cancelHours",e.target.value)}/></Field><Field label="Sede / lugar"><input value={form.place||""} onChange={e=>value("place",e.target.value)}/></Field><Field label="Rutina vinculada" full><select value={form.structureId||""} onChange={e=>value("structureId",e.target.value)}><option value="">Sin rutina</option>{by("structure").map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field></>}<Field label="Inicio"><input type="time" required value={form.start||"07:00"} onChange={e=>value("start",e.target.value)}/></Field><Field label="Fin"><input type="time" required min={form.start||"07:00"} value={form.end||"08:00"} onChange={e=>value("end",e.target.value)}/></Field></>}
 {modal==="payment"&&<><Field label="Atleta" full><select required value={form.athleteId||""} onChange={e=>value("athleteId",e.target.value)}><option value="">Selecciona…</option>{by("athlete").map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Concepto" full><input required value={form.concept||""} onChange={e=>value("concept",e.target.value)}/></Field><Field label="Monto"><input required type="number" min="0" step="0.01" value={form.amount||""} onChange={e=>value("amount",e.target.value)}/></Field><Field label="Créditos a acreditar"><input type="number" min="0" value={form.creditAmount||""} onChange={e=>value("creditAmount",e.target.value)}/></Field><Field label="Método"><select value={form.method||"Efectivo"} onChange={e=>value("method",e.target.value)}>{["Efectivo","Transferencia","Tarjeta","Otro"].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Estatus"><select value={form.status||"Pagado"} onChange={e=>value("status",e.target.value)}><option>Pagado</option><option>Pendiente</option></select></Field><Field label="Fecha"><input type="date" value={form.date||today()} onChange={e=>value("date",e.target.value)}/></Field><Field label="Vence"><input type="date" value={form.due||""} onChange={e=>value("due",e.target.value)}/></Field><Field label="Recurrencia" full><select value={form.recurrence||"Ninguna"} onChange={e=>value("recurrence",e.target.value)}>{["Ninguna","Semanal","Mensual"].map(x=><option key={x}>{x}</option>)}</select></Field></>}
 {modal==="product"&&<><Field label="Nombre" full><input required value={form.name||""} onChange={e=>value("name",e.target.value)}/></Field><Field label="Categoría"><select value={form.category||"Suplementación"} onChange={e=>value("category",e.target.value)}>{["Suplementación","Ropa y Accesorios","Programas Digitales"].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Precio base"><input type="number" min="0" step="0.01" required value={form.price||""} onChange={e=>value("price",e.target.value)}/></Field><Field label="Descripción" full><textarea value={form.description||""} onChange={e=>value("description",e.target.value)}/></Field><Field label="Especificaciones" full><textarea value={form.specifications||""} onChange={e=>value("specifications",e.target.value)}/></Field><Field label="Enlace de imagen" full><input type="url" placeholder="https://…" value={form.imageUrl||""} onChange={e=>value("imageUrl",e.target.value)}/></Field><Field label="Enlace de archivo digital" full><input type="url" placeholder="https://…" value={form.fileUrl||""} onChange={e=>value("fileUrl",e.target.value)}/></Field><label className="full check"><input type="checkbox" checked={!!form.digital} onChange={e=>value("digital",e.target.checked)}/> Producto digital</label><Field label="Stock mínimo"><input type="number" min="0" value={form.minStock||0} onChange={e=>value("minStock",e.target.value)}/></Field><div className="full"><span className="label">Variantes (talla / color / sabor)</span>{(form.variants||[]).map((v:any,i:number)=><div className="variant-grid" key={i}><input placeholder="Variante" value={v.name||""} onChange={e=>value("variants",form.variants.map((x:any,j:number)=>j===i?{...x,name:e.target.value}:x))}/><input type="number" min="0" placeholder="Stock" value={v.stock??0} onChange={e=>value("variants",form.variants.map((x:any,j:number)=>j===i?{...x,stock:e.target.value}:x))}/><button type="button" onClick={()=>value("variants",form.variants.filter((_:any,j:number)=>i!==j))} aria-label="Quitar variante"><X size={17}/></button></div>)}<button className="secondary" type="button" onClick={()=>value("variants",[...(form.variants||[]),{name:"",stock:0}])}><Plus size={16}/> Añadir variante</button></div></>}
 <button className="primary save" disabled={busy}>{busy?"Guardando…":"Guardar"}</button></form></DialogContent></Dialog>
 <Dialog open={dayOpen} onOpenChange={setDayOpen}><DialogContent className="day-dialog"><DialogHeader><DialogTitle>{niceDate(day)}</DialogTitle></DialogHeader>{dayItems.length?dayItems.map(x=><p key={x.id}><b>{x.start}–{x.end}</b> · {x.title}</p>):<p>Sin actividad este día. Crea una sesión o bloquea tu tiempo.</p>}<button className="primary" onClick={()=>{setDayOpen(false);open("session")}}><Plus size={17}/> Nuevo en agenda</button></DialogContent></Dialog>
 <Dialog open={cartOpen} onOpenChange={setCartOpen}><DialogContent className="editor"><DialogHeader><DialogTitle>Carrito</DialogTitle></DialogHeader>{cart.length?<form onSubmit={placeOrder} className="form-grid">{cart.map(x=><div className="cart-row full" key={x.id}>{by("product").find(p=>p.id===x.id)?.name}<div><button type="button" onClick={()=>setCart(c=>c.map(y=>y.id===x.id?{...y,qty:Math.max(1,y.qty-1)}:y))}>−</button><b>{x.qty}</b><button type="button" onClick={()=>setCart(c=>c.map(y=>y.id===x.id?{...y,qty:y.qty+1}:y))}>+</button><button type="button" onClick={()=>setCart(c=>c.filter(y=>y.id!==x.id))} aria-label="Quitar"><X size={16}/></button></div></div>)}<strong className="full">Total: {money(cartTotal)}</strong><Field label="Cliente" full><input required value={form.customer||""} onChange={e=>value("customer",e.target.value)}/></Field><Field label="Entrega"><select value={form.fulfillment||"Recoger en estudio"} onChange={e=>value("fulfillment",e.target.value)}><option>Recoger en estudio</option><option>Envío</option><option>Digital</option></select></Field><Field label="Método"><select value={form.method||"Efectivo"} onChange={e=>value("method",e.target.value)}><option>Efectivo</option><option>Transferencia</option><option>Tarjeta</option></select></Field><button className="primary save" disabled={busy}>Registrar pedido</button></form>:<Empty>Tu carrito está vacío.</Empty>}</DialogContent></Dialog>
 </div>;
}
