'use client';
import {useEffect,useState} from 'react';
import {hasRole,roleLabels,type Identity,type Role} from '@/lib/roles';
type Account=Identity & {username:string|null;active:boolean};
type Athlete={id:string;name:string;ownerId:string};
const api=`${process.env.NEXT_PUBLIC_BASE_PATH}/api/users/`;
export default function AccountManager({user,onChanged}:{user:Identity;onChanged?:(instructors:Identity[])=>void}){
  const [accounts,setAccounts]=useState<Account[]>([]),[athletes,setAthletes]=useState<Athlete[]>([]),[instructors,setInstructors]=useState<Account[]>([]),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
  const [type,setType]=useState('student'),[form,setForm]=useState({name:'',username:'',password:'',athleteId:'',email:'',roles:['instructor'] as Role[]});
  async function load(){const r=await fetch(api),j:any=await r.json();if(!r.ok)throw new Error(j.error);setAccounts(j.users);setAthletes(j.athletes);setInstructors(j.instructors);onChanged?.(j.instructors);}
  useEffect(()=>{load().catch(e=>setError(e.message));},[]);
  async function send(method:string,body:unknown){setError('');setMessage('');setBusy(true);try{const r=await fetch(api,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),j:any=await r.json();if(!r.ok)throw new Error(j.error);await load();setMessage('Cuenta actualizada.');return true;}catch(e){setError(e instanceof Error?e.message:'No se pudo guardar');return false;}finally{setBusy(false);}}
  async function create(e:React.FormEvent){e.preventDefault();if(await send('POST',{...form,type})){setForm({...form,name:'',username:'',password:'',athleteId:'',email:''});setMessage(type==='student'?'Cuenta creada. Comparte el usuario y la contraseña temporal con el alumno; deberá cambiarla al entrar.':'Cuenta de Google autorizada.');}}
  async function reset(account:Account){const password=window.prompt(`Nueva contraseña temporal para ${account.name} (mínimo 12 caracteres):`);if(password!==null)await send('PATCH',{id:account.id,password});}
  return <section><header className="page-head"><div><h1>Usuarios y accesos</h1><p>Cuentas de alumnos{hasRole(user,'admin')?' y permisos del equipo':''}.</p></div></header>{error&&<p role="alert" className="notice error">{error}</p>}{message&&<p role="status" className="notice">{message}</p>}
    <article className="card"><h2>Crear acceso</h2><form className="form-grid" onSubmit={create}>{hasRole(user,'admin')&&<label className="field full">Tipo<select value={type} onChange={e=>setType(e.target.value)}><option value="student">Alumno · usuario y contraseña</option><option value="google">Equipo · Google</option></select></label>}
      <label className="field full">Nombre<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} maxLength={150}/></label>
      {type==='student'?<><label className="field full">Ficha de atleta<select required value={form.athleteId} onChange={e=>{const athlete=athletes.find(a=>a.id===e.target.value);setForm({...form,athleteId:e.target.value,name:athlete?.name||form.name});}}><option value="">Selecciona una ficha existente…</option>{athletes.filter(a=>!accounts.some(u=>u.athleteId===a.id)).map(a=><option key={a.id} value={a.id}>{a.name}{hasRole(user,'admin')?` · ${instructors.find(i=>i.id===a.ownerId)?.name||'Instructor'}`:''}</option>)}</select></label><label className="field">Usuario<input required autoComplete="off" value={form.username} onChange={e=>setForm({...form,username:e.target.value})} minLength={3} maxLength={50} pattern="[a-zA-Z0-9][a-zA-Z0-9._\-]{2,49}"/></label><label className="field">Contraseña temporal<input required type="password" autoComplete="new-password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} minLength={12} maxLength={256}/></label></>:<><label className="field full">Correo de Google<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><div className="full"><span>Roles</span>{(['admin','instructor','support'] as Role[]).filter(r=>r!=='support'||hasRole(user,'support')).map(role=><label key={role} className="check"><input type="checkbox" checked={form.roles.includes(role)} onChange={e=>setForm({...form,roles:e.target.checked?[...form.roles,role]:form.roles.filter(r=>r!==role)})}/>{roleLabels[role]}</label>)}</div></>}
      <button className="primary save" disabled={busy}>{busy?'Guardando…':'Crear cuenta'}</button>
    </form></article><h2>Cuentas existentes</h2><div className="cards">{accounts.map(account=><article key={account.id} className="card"><h3>{account.name}</h3><p>{account.email||account.username}</p><div className="tags">{account.roles.map(r=><span key={r}>{roleLabels[r]}</span>)}<span>{account.active?'Activa':'Desactivada'}</span>{account.mustChangePassword&&<span>Contraseña temporal</span>}</div>{account.id!==user.id&&<div className="account-actions"><button className="secondary" disabled={busy} onClick={()=>{if(window.confirm(`¿${account.active?'Desactivar':'Activar'} la cuenta de ${account.name}?`))void send('PATCH',{id:account.id,active:!account.active});}}>{account.active?'Desactivar':'Activar'}</button>{account.roles.includes('student')?<button className="secondary" disabled={busy} onClick={()=>reset(account)}>Restablecer contraseña</button>:hasRole(user,'admin')&&(!account.roles.includes('support')||hasRole(user,'support'))&&<fieldset><legend>Permisos</legend>{(['admin','instructor','support'] as Role[]).filter(r=>r!=='support'||hasRole(user,'support')).map(role=><label key={role} className="check"><input type="checkbox" disabled={busy} checked={account.roles.includes(role)} onChange={e=>{const roles=e.target.checked?[...account.roles,role]:account.roles.filter(r=>r!==role);if(window.confirm(`¿Actualizar los permisos de ${account.name}? Se cerrarán sus sesiones.`))void send('PATCH',{id:account.id,roles});}}/>{roleLabels[role]}</label>)}</fieldset>}</div>}</article>)}</div>
  </section>;
}
