'use client';
import {useEffect,useState} from 'react';
import {type Identity} from '@/lib/roles';
type Rec={id:string;kind:string;[key:string]:any};
const base=process.env.NEXT_PUBLIC_BASE_PATH||'/OwensFitness';
export default function StudentApp({user}:{user:Identity}){
  const [records,setRecords]=useState<Rec[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[change,setChange]=useState(user.mustChangePassword),[password,setPassword]=useState({currentPassword:'',password:''}),[notes,setNotes]=useState<Record<string,string>>({});
  async function load(){const r=await fetch(`${base}/api/records/`),j:any=await r.json();if(!r.ok)throw new Error(j.error);setRecords(j.records);}
  useEffect(()=>{if(!change)void load().catch(e=>setError(e.message));},[change]);
  async function changePassword(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await fetch(`${base}/api/password/`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(password)}),j:any=await r.json();if(!r.ok)throw new Error(j.error);setPassword({currentPassword:'',password:''});setChange(false);}catch(e){setError(e instanceof Error?e.message:'No se pudo cambiar');}finally{setBusy(false);}}
  async function advance(sessionId:string){setBusy(true);setError('');try{const r=await fetch(`${base}/api/records/`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:'progress',data:{sessionId,notes:notes[sessionId]||'',completed:true}})}),j:any=await r.json();if(!r.ok)throw new Error(j.error);setNotes({...notes,[sessionId]:''});await load();}catch(e){setError(e instanceof Error?e.message:'No se pudo registrar');}finally{setBusy(false);}}
  return <main className="student-shell"><header className="page-head"><div><h1>Mi entrenamiento</h1><p>{user.name}</p></div><div className="head-actions">{!change&&<button className="secondary" onClick={()=>setChange(true)}>Cambiar contraseña</button>}<button className="secondary" onClick={async()=>{await fetch(`${base}/api/logout/`,{method:'POST'});window.location.href=`${base}/login/`;}}>Cerrar sesión</button></div></header>{error&&<p role="alert" className="notice error">{error}</p>}
    {change?<article className="card"><h2>{user.mustChangePassword?'Cambia tu contraseña temporal':'Cambiar contraseña'}</h2><form className="form-grid" onSubmit={changePassword}><label className="field">Contraseña actual<input required type="password" autoComplete="current-password" value={password.currentPassword} onChange={e=>setPassword({...password,currentPassword:e.target.value})} maxLength={256}/></label><label className="field">Nueva contraseña<input required type="password" autoComplete="new-password" minLength={12} maxLength={256} value={password.password} onChange={e=>setPassword({...password,password:e.target.value})}/></label><button className="primary save" disabled={busy}>Guardar contraseña</button></form></article>:<><h2>Mis sesiones y rutinas</h2><div className="cards">{records.filter(r=>r.kind==='session').sort((a,b)=>`${a.date}${a.start}`.localeCompare(`${b.date}${b.start}`)).map(session=>{const structure=records.find(r=>r.id===session.structureId&&r.kind==='structure');return <article className="card" key={session.id}><h3>{session.title}</h3><p>{session.date} · {session.start}–{session.end} · {session.place}</p>{structure&&<><h3>{structure.name}</h3><p>{structure.description}</p><ul>{(structure.moves||[]).map((move:any,i:number)=><li key={i}>{records.find(r=>r.id===move.exerciseId)?.name||'Ejercicio'} · {move.reps}{move.load&&` · ${move.load}`}{move.rpe&&` · RPE ${move.rpe}`}</li>)}</ul></>}<label className="field">Mi avance<textarea maxLength={3000} placeholder="Repeticiones, carga, sensaciones…" value={notes[session.id]||''} onChange={e=>setNotes({...notes,[session.id]:e.target.value})}/></label><button className="primary" disabled={busy} onClick={()=>advance(session.id)}>Registrar entrenamiento completado</button>{records.filter(r=>r.kind==='progress'&&r.sessionId===session.id).map(progress=><div className="progress-entry" key={progress.id}><strong>{progress.date} · Completado</strong><p>{progress.notes}</p></div>)}</article>;})}</div>{!records.some(r=>r.kind==='session')&&<p className="empty">Tu instructor todavía no te ha asignado sesiones.</p>}
    <h2>Mis pagos</h2><div className="cards">{records.filter(r=>r.kind==='payment').map(payment=><article className="card" key={payment.id}><h3>{payment.concept}</h3><p>{new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format(Number(payment.amount)||0)} · {payment.status} · {payment.date}</p></article>)}</div></>}
  </main>;
}
